### ISSUE TITLE
Closing a bundle after depeg and before process last price

### ISSUE THREAD

**Issue by doerfli** [etherisc/depeg-contracts#16]
<img width="594" alt="Cursor_and_Untitled" src="https://user-images.githubusercontent.com/7255610/215498874-126cf447-f6ca-4bee-81bf-284cb47b8ffe.png">

- depeg happens at 10.00
- policy expires at 10.01 (before any claim is made)
- bundle is closed at 10.04 (still before any claim is made) and all funds are withdrawn as no claims are locking any funds
- last prices are processed at 10.05 - 💥

**Comment by matthiaszimmermann** [comment]
not an issue: precondition to close a bundle is that it does not have open policies. policies need to be explicitly closed first. either through explicit close function or by claiming and processing the claims. 

earliest point to close the bundle in this situation would be: investor closes all open policies that have not yet claimed after claim grace period. policies that have claimed need to go processing by product owner before investor can close the bundle
