### ISSUE TITLE
[Bug]: Apply for policy creates policy on bundle without checking stakes

### ISSUE THREAD

**Issue by doerfli** [etherisc/depeg-contracts#19]
### What happened?

- create some bundles and stake DIPs on them
- create one bundle with very low apr and wide min/max range (should cover most of the above bundles)
- call `applyForNewPolicy` for one of the staked bundles but the values would also match with the latest (unstaked bundle)

-> policy was added to the **unstaked** bundle

### What operating system are you seeing the problem on?

Mac OS

### What browsers are you seeing the problem on?

Firefox

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by matthiaszimmermann** [comment]
caused by removed restriction in contract:


        // commented code below to indicate how to enforce hard link to stking in this contract
        // if(getSupportedCapitalAmount(bundle.id) < bundle.lockedCapital + application.sumInsuredAmount) {
        //     sumInsuredOk = false;
        // }

will adapt depeg product in a way that frontend forces the choice of the bundle that secures the application

**Comment by doerfli** [comment]
bounty paid

**Comment by doerfli** [comment]
update to ui has been pushed and its now possible to select the bundle during signup.
